### ISSUE TITLE
Recently, mfc_cb.node dies (events.js:160)

### ISSUE THREAD

**Issue by ms6676749** [jrudess/mfc_cb.node#23]
OS: Win7 x64
NodeJS: v6.11.0

I typically run mfc_cb.node via a bat file.  When I ran it the first time, everything went fine.  Then CB stopped being polled at random (likely a server side issue) and recently, mfc_cb.node crashes.  I never had a chance to grabbed the error message, but I insert a pause at the end of my bat to see if anything was left behind, here it is below.  Now, I did upgrade to this current version of NodeJS by overwriting the old version.  Should I try a clean install of v6.11.0?
```
[20170701_1232_04] MFC [DEBUG] Model#1 is already capturing
[20170701_1232_04] MFC [DEBUG] Done, waiting 120 seconds.
[20170701_1233_45] CB  [DEBUG] 5 model(s) to capture
[20170701_1233_46] CB  [DEBUG] Done, waiting 120 seconds.
[20170701_1234_04] MFC [DEBUG] Model#1 file size (Model#1-MFC_XXXXXX.ts), size=83410900, maxByteSize=250000000
[20170701_1234_05] MFC [DEBUG] 1 model(s) to capture
[20170701_1234_05] MFC [DEBUG] Model#1 is already capturing
[20170701_1234_05] MFC [DEBUG] Done, waiting 120 seconds.
[20170701_1235_46] MFC Model#1 converting to Model#1-MFC_XXXXXXXXX.mp4
[20170701_1236_07] CB  [ERROR] ConnectionTimeoutError: The connection timed out.

Code: 606
request: undefined
requestState: undefined
[20170701_1236_07] CB  [DEBUG] 5 model(s) to capture
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)
Press any key to continue . . .
```

**Comment by ms6676749** [comment]
For some reason or another the problem has abated for now.  I am assuming this, again, is a server side issue.

**Comment by jrudess** [comment]
I've mostly only seen this for local network/ISP issues, but it probably would happen on a server-side issue as well.  

The mfc.node base repo for this project started seeing this after switching to MFCAuto, so my suspicion is that there is some unhandled exception in that logic, so this probably can be fixed.   But I have no proof for these suspicions yet.

**Comment by jrudess** [comment]
Integrated newer version of MFCAuto and switched to websocket connections.  A problem with MFCAuto exception handlers that made debugging disconnections difficult was fixed.   Please upgrade to v0.5.0 and poste any new connection errors you run into.

**Comment by jrudess** [comment]
I haven't seen this in a week, tentatively closing this sighting, but feel free to reopen if it still is an issue for you.
