### ISSUE TITLE
Consistent error 

### ISSUE THREAD

**Issue by jackusm** [jrudess/mfc_cb.node#7]
`[20170320-194133] CB  [ERROR] TypeError: Cannot read property 'length' of null
    at processUpdates (/media/sde1/home/jackus/repos/mfc_cb.node/main.js:41:36)
    at /media/sde1/home/jackus/repos/mfc_cb.node/main.js:244:12
    at tryCatcher (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/method.js:31:24)
    at getModelsToCap (/media/sde1/home/jackus/repos/mfc_cb.node/main.js:243:21)
    at /media/sde1/home/jackus/repos/mfc_cb.node/main.js:421:14
    at tryCatcher (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
[20170320-194133] CB  [ERROR] TypeError: Cannot read property 'length' of undefined
    at /media/sde1/home/jackus/repos/mfc_cb.node/main.js:428:22
    at tryCatcher (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/media/sde1/home/jackus/repos/mfc_cb.node/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
[20170320-194133] CB  Done, will search for new models in 30 second(s).`
I get this every 30s (or whatever my config setting is). Also I'm not sure if it's related but my ffmpeg stops recording/writing after a while (less than a few minutes but very random in how long) except it doesn't error out so I have the process lingering while mfc_cb believes it is still recording, until I end the process of course at which point it converts the recording and then repeats the whole process over with each model

**Comment by jackusm** [comment]
Switched to the development branch and seems to be working. Also I reinstalled npm with -g not sure if that made any difference maybe something installed wrong the first time around

**Comment by jrudess** [comment]
Thanks for submitting the report as it reminds me to pull the development branch fixes and make a release.
